services:
  db: 
    image: postgres:17.2
    volumes: 
      - data:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: 12345
    ports: 
      - "5432:5432"


  backend: 
    build: ./backend 
    depends_on: 
      - db 
    ports: 
      - "8080:8080"

volumes: 
  data:
